project:
  type: website
  output-dir: docs

website:
  title: "Isaiah Moliga-Puletasi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu:
        - href: dataviz.qmd
          text: Total number of sheep in New Zealand (1935-2024)
        - href: dataviz1.qmd
          text: Number of art pieces across NY transit (2025)

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



